import type { LucideIcon, LucideProps } from 'lucide-react';
import {
  AlignLeft,
  AlertTriangle,
  ArrowLeft,
  Banknote,
  BarChart3,
  Bell,
  ChevronDown,
  ChevronRight,
  ClipboardList,
  Columns3,
  Database,
  FileText,
  Filter,
  Home,
  LayoutGrid,
  LogOut,
  Menu,
  Receipt,
  RefreshCw,
  Settings,
  Ticket,
  Upload,
  Users,
  UsersRound,
  Wrench,
  X,
  ArrowRight,
  Bath,
  BedDouble,
  Building2,
  Calendar,
  CalendarClock,
  Car,
  Check,
  ChevronLeft,
  CircleAlert,
  Clock,
  Compass,
  Download,
  ExternalLink,
  Eye,
  Globe,
  Grid2x2,
  ImageIcon,
  Mail,
  MapPin,
  MoreHorizontal,
  Pencil,
  Percent,
  Phone,
  Plus,
  Ruler,
  Search,
  Sparkles,
  Trash2,
  TrendingDown,
  TrendingUp,
  Wallet,
} from 'lucide-react';

const ICONS = {
  // Nav items
  dashboard: LayoutGrid,
  properties: Home,
  persons: Users,
  leads: Filter,
  pipeline: Columns3,
  contracts: FileText,
  liquidaciones: Banknote,
  renditions: ClipboardList,
  invoices: Receipt,
  reports: BarChart3,
  services: Wrench,
  providers: UsersRound,
  tickets: Ticket,
  import: Upload,
  migration: Database,
  settings: Settings,
  delinquency: AlertTriangle,
  // UI chrome
  arrowLeft: ArrowLeft,
  chevronLeft: ChevronLeft,
  menu: Menu,
  close: X,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  logout: LogOut,
  bell: Bell,
  collapse: AlignLeft,
  text: AlignLeft,
  refresh: RefreshCw,
  // Card system — actions, metadata, trends
  arrowRight: ArrowRight,
  mail: Mail,
  phone: Phone,
  building: Building2,
  wallet: Wallet,
  percent: Percent,
  calendar: Calendar,
  calendarClock: CalendarClock,
  check: Check,
  alert: CircleAlert,
  clock: Clock,
  download: Download,
  externalLink: ExternalLink,
  view: Eye,
  image: ImageIcon,
  mapPin: MapPin,
  more: MoreHorizontal,
  edit: Pencil,
  plus: Plus,
  search: Search,
  sparkles: Sparkles,
  trash: Trash2,
  trendingDown: TrendingDown,
  trendingUp: TrendingUp,
  // Property features
  area: Ruler,
  rooms: Grid2x2,
  bedrooms: BedDouble,
  bathrooms: Bath,
  garages: Car,
  orientation: Compass,
  country: Globe,
} as const;

export type IconName = keyof typeof ICONS;

export function Icon({ name, ...props }: { name: IconName } & LucideProps) {
  const Component: LucideIcon = ICONS[name];
  return <Component aria-hidden {...props} />;
}
